import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });
import { WalletProviderWrapper } from "@/context/Wallet";
import { SongPlayerProvider } from "@/context/SongPlayerContext";
import { PlaylistProvider } from "@/context/PlaylistContext";
export const metadata: Metadata = {
  title: "Solify - Web3 Player: Music for everyone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PlaylistProvider>
          <SongPlayerProvider>
            <WalletProviderWrapper>
              <ToastContainer
                position="top-right"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="dark"
              />
              <div className="md:hidden grid place-items-center w-full h-full">
                <div className="">
                  <Image src={`/music-bird.svg`} width="200" height="24" alt="music-bird" className="block mx-auto"/>
                  <p className="text-white font-mono font-bold mt-2 text-center">Unfortunately! this is for larger screens only</p>
                </div>
              </div>
              <div className="w-full h-full md:block hidden">
                <div className="grid grid-cols-12 grid-rows-10 grid-flow-dense h-full gap-2">
                  <div className="col-span-3 col-start-1 row-span-9 row-start-1 overflow-hidden">
                    <Sidebar></Sidebar>
                  </div>
                  <div className="col-span-9 row-span-9 row-start-1 col-start-4 bg-neutral-900 p-2 overflow-y-scroll">
                    {children}
                  </div>
                  <div className="col-span-12 col-start-1 row-span-1 row-start-10">
                    <Footer></Footer>
                  </div>
                </div>
              </div>
            </WalletProviderWrapper>
          </SongPlayerProvider>
        </PlaylistProvider>
      </body>
    </html>
  );
}
